version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskmanager
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy &&
             npm start"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"   # Nginx serves production frontend on port 80
    depends_on:
      - backend

volumes:
  db_data:
